// Code generated by protoc-gen-go.
// source: qrtalker.proto
// DO NOT EDIT!

/*
Package Transport is a generated protocol buffer package.

It is generated from these files:
	qrtalker.proto

It has these top-level messages:
	QRRequest
	QRResponse
*/
package Transport

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QRRequest struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type      string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Authtoken string `protobuf:"bytes,3,opt,name=authtoken" json:"authtoken,omitempty"`
	Datalen   int32  `protobuf:"varint,4,opt,name=datalen" json:"datalen,omitempty"`
	Data      string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *QRRequest) Reset()                    { *m = QRRequest{} }
func (m *QRRequest) String() string            { return proto.CompactTextString(m) }
func (*QRRequest) ProtoMessage()               {}
func (*QRRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type QRResponse struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Err     string `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
	Datalen int32  `protobuf:"varint,4,opt,name=datalen" json:"datalen,omitempty"`
	Data    []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *QRResponse) Reset()                    { *m = QRResponse{} }
func (m *QRResponse) String() string            { return proto.CompactTextString(m) }
func (*QRResponse) ProtoMessage()               {}
func (*QRResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*QRRequest)(nil), "Transport.QRRequest")
	proto.RegisterType((*QRResponse)(nil), "Transport.QRResponse")
}

func init() { proto.RegisterFile("qrtalker.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x3d, 0xca, 0xc3, 0x30,
	0x0c, 0x40, 0x71, 0x7e, 0xbe, 0x0f, 0x8b, 0x12, 0x8a, 0x27, 0x0f, 0x1d, 0x42, 0xa6, 0x4c, 0x5d,
	0x7a, 0x92, 0x9a, 0x5e, 0xc0, 0x25, 0x82, 0x86, 0x04, 0xdb, 0x91, 0x95, 0xa1, 0xf4, 0xf2, 0xc5,
	0x4e, 0x4b, 0xd7, 0x6c, 0x4f, 0x12, 0xbc, 0x07, 0x82, 0x66, 0x21, 0xb6, 0xf3, 0x84, 0x74, 0x0e,
	0xe4, 0xd9, 0x2b, 0x79, 0x23, 0xeb, 0x62, 0xf0, 0xc4, 0xdd, 0x0b, 0xe4, 0xd5, 0x18, 0x5c, 0x56,
	0x8c, 0xac, 0x1a, 0x28, 0xc6, 0x41, 0x8b, 0x56, 0xf4, 0xa5, 0x29, 0xc6, 0x41, 0x29, 0xa8, 0xf8,
	0x19, 0x50, 0x17, 0xad, 0xe8, 0xa5, 0xc9, 0xac, 0x4e, 0x20, 0xed, 0xca, 0x0f, 0xf6, 0x13, 0x3a,
	0x5d, 0xe6, 0xc3, 0x6f, 0xa1, 0x34, 0xfc, 0x0f, 0x96, 0xed, 0x8c, 0x4e, 0x57, 0xad, 0xe8, 0x6b,
	0xf3, 0x1d, 0x93, 0x2b, 0xa1, 0xae, 0x37, 0x57, 0xe2, 0x2e, 0x00, 0xa4, 0x78, 0x0c, 0xde, 0x45,
	0xdc, 0x55, 0x3f, 0x42, 0x89, 0x44, 0x9f, 0x6e, 0xc2, 0x9d, 0xc5, 0xc3, 0x56, 0xbc, 0xff, 0xe5,
	0x07, 0x5c, 0xde, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1c, 0xaf, 0x71, 0xf6, 0x12, 0x01, 0x00, 0x00,
}
